#!/usr/bin/env node
// Generates src/version.ts from package.json so the exported VERSION constant
// can never drift from the published package version. Runs on `prepare`
// (post-install) and at the start of `build`. The generated file is gitignored.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const target = join(root, 'src', 'version.ts');

const contents = `// AUTO-GENERATED by scripts/gen-version.mjs from package.json — do not edit.
export const VERSION = '${version}';
`;

writeFileSync(target, contents);
